version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: webrtc-vlm-backend/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:5000
    volumes:
      - ./webrtc-vlm-frontend/public/models:/app/models
    networks:
      - webrtc-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://backend:5000
    networks:
      - webrtc-network

networks:
  webrtc-network:
    driver: bridge

